### ISSUE TITLE
error in detect_leaf_markers

### ISSUE THREAD

**Issue by xyang2uchicago** [pinellolab/STREAM#150]
Hi, 
My code running the Jupyter Notebook is:
> st.detect_leaf_markers(adata,marker_list=adata.uns['var_genes'],cutoff_zscore=1.0,cutoff_pvalue=0.01,
...                         percentile_expr=90, min_num_cells=25,
...                        root='S0',n_jobs=1)

The error outputs are:
>Scanning the specified marker list ...
Filtering out markers that are expressed in less than 25 cells ...
1 cpus are being used ...
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/project/xyang2/software-packages/env/stream/lib/python3.7/site-packages/stream/core.py", line 3807, in detect_leaf_markers
    results = pool.map(scale_marker_expr,params)
  File "/project/xyang2/software-packages/env/stream/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/project/xyang2/software-packages/env/stream/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/project/xyang2/software-packages/env/stream/lib/python3.7/multiprocessing/pool.py", line 431, in _handle_tasks
    put(task)
  File "/project/xyang2/software-packages/env/stream/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/project/xyang2/software-packages/env/stream/lib/python3.7/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647

Anyone can help?

**Comment by HHAHAXY** [comment]
Hello!
I have the same problem. It looks like an issue with pool multiprocessing which was [fixed](https://stackoverflow.com/questions/47776486/python-struct-error-i-format-requires-2147483648-number-2147483647) in py3.8. However, STREAM 1.1 only supports py3.7. As a temporary fix, I reduced the number of genes (marker_list parameter).
