### ISSUE TITLE
Error when Extract Branches

### ISSUE THREAD

**Issue by readline** [pinellolab/STREAM#72]
Hi, team,
Recently I came up with an issue when analyzing scRNA-seq data. It was done with singularity image, and I had successfully finished full analysis with another batch of ~6000 zebrafish cell. So, I don't think it was an environment or species problem.
Here it is the log:

Loading input data...
Input: 10713 cells, 20526 genes
remove mitochondrial genes:
['mt-nd1', 'mt-nd2', 'mt-co1', 'mt-co2', 'mt-atp8', 'mt-atp6', 'mt-co3', 'mt-nd3', 'mt-nd4l', 'mt-nd4', 'mt-nd5', 'mt-nd6', 'mt-cyb']
Filtering genes...
After filtering out low-expressed genes: 
10713 cells, 10613 genes
Number of CPUs being used: 48
Reducing dimension...
Structure Learning...
Clustering...
Minimum Spanning Tree...
Number of initial branches: 147
Elastic Principal Graph...
[1] "Constructing tree 1 of 1 / Subset 1 of 1"
[1] "Computing EPG with 319 nodes on 10713 points and 3 dimensions"
[1] "Using a single core"
Nodes = 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306 307 308 309 310 311 312 313 314 315 316 317 318 
BARCODE	ENERGY	NNODES	NEDGES	NRIBS	NSTARS	NRAYS	NRAYS2	MSE	MSEP	FVE	FVEP	UE	UR	URN	URN2	URSD
6|41||319	2.02e-05	319	318	217	41	0	0	1.004e-05	9.979e-06	0.9641	0.9644	9.791e-06	3.617e-070.0001154	0.0368	0
6116.885 sec elapsed
[[1]]

Number of branches after initial ElPiGraph: 101
Collasping small branches ...
[1] "Removing the bridge branch with nodes: 6 21"
[1] "Removing the bridge branch with nodes: 8 156"
[1] "Removing the terminal branch with nodes: 8 43 195"
[1] "Removing the bridge branch with nodes: 10 150 46 15 207"
[1] "Removing the terminal branch with nodes: 18 16 130"
[1] "Removing the bridge branch with nodes: 24 135"
[1] "Removing the terminal branch with nodes: 24 113 197 29 187 172 255 53 234"
[1] "Removing the bridge branch with nodes: 37 152"
[1] "Removing the terminal branch with nodes: 37 22 51 3 147"
[1] "Removing the bridge branch with nodes: 56 116"
[1] "Removing the terminal branch with nodes: 56 159 83"
[1] "Removing the terminal branch with nodes: 59 111"
[1] "Removing the bridge branch with nodes: 74 89"
[1] "Removing the terminal branch with nodes: 74 121"
[1] "Removing the bridge branch with nodes: 81 104"
[1] "Removing the bridge branch with nodes: 89 99 120"
[1] "Removing the bridge branch with nodes: 103 120"
[1] "Removing the terminal branch with nodes: 103 110"
[1] "Removing the terminal branch with nodes: 103 117"
[1] "Removing the terminal branch with nodes: 116 243 12 82"
[1] "Removing the terminal branch with nodes: 116 76 108"
[1] "Removing the terminal branch with nodes: 120 68 124"
[1] "Removing the bridge branch with nodes: 136 207"
[1] "Removing the terminal branch with nodes: 136 102"
[1] "Removing the bridge branch with nodes: 151 218"
[1] "Removing the terminal branch with nodes: 151 258 162 217"
[1] "Removing the bridge branch with nodes: 152 141 169 237"
[1] "Removing the bridge branch with nodes: 158 225"
[1] "Removing the bridge branch with nodes: 171 237"
[1] "Removing the terminal branch with nodes: 171 166"
[1] "Removing the terminal branch with nodes: 171 204 235"
[1] "Removing the bridge branch with nodes: 177 225"
[1] "Removing the terminal branch with nodes: 177 160 180"
[1] "Removing the bridge branch with nodes: 190 207"
[1] "Removing the terminal branch with nodes: 190 27"
[1] "Removing the terminal branch with nodes: 190 65"
[1] "Removing the terminal branch with nodes: 190 126 79"
[1] "Removing the terminal branch with nodes: 225 75 64"
[1] "Removing the terminal branch with nodes: 237 196"
[1] "Removing the terminal branch with nodes: 238 254"
[1] "Constructing tree 1 of 1 / Subset 1 of 1"
[1] "Computing EPG with 279 nodes on 10713 points and 3 dimensions"
[1] "Using a single core"
Nodes = 249 250 251 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 277 278 
BARCODE	ENERGY	NNODES	NEDGES	NRIBS	NSTARS	NRAYS	NRAYS2	MSE	MSEP	FVE	FVEP	UE	UR	URN	URN2	URSD
1|3|2|13||279	1.409e-05	279	278	228	13	0	0	8.368e-06	8.289e-06	0.9701	0.9704	5.233e-06	4.93e-07	0.0001376	0.03838	0
538.464 sec elapsed
Number of branches after optimization: 50
Extending leaves with additional nodes ...
Traceback (most recent call last):
  File "/STREAM/STREAM.py", line 4033, in <module>
    main()
  File "/STREAM/STREAM.py", line 3957, in main
    n_processes,input_cell_label_uni,input_cell_label_uni_color,file_path,file_path_precomp,flag_web)
  File "/STREAM/STREAM.py", line 851, in Structure_Learning
    dict_branches = Extract_Branches(EPG)
  File "/STREAM/STREAM.py", line 514, in Extract_Branches
    dict_branches = Cal_Branch_Length(EPG,dict_branches)
  File "/STREAM/STREAM.py", line 487, in Cal_Branch_Length
    br_nodes_pos = np.array([dict_nodes_pos[i] for i in nodes]) 
KeyError: 310

**Comment by readline** [comment]
BTW, default configs were used.

**Comment by readline** [comment]
This issue disappeared when switching from 0.1.0 to a 0.3.8 version.
