### ISSUE TITLE
Error when running python commandline.

### ISSUE THREAD

**Issue by smk5g5** [pinellolab/STREAM#83]
I am getting this error when I try to run it directly through python script any particular reason for this?

Also for some reason qc plots are not saved even if I specify 'save_fig=True'.

`st.plot_qc(adata,jitter=0.3,save_fig=True,fig_name='qc.pdf')
st.plot_qc(adata,jitter=0.3,log_scale=[0,1,4,5],hist_plot=[0,1,4,5],save_fig=True,fig_name='qc2.pdf')`

`Traceback (most recent call last):
  File "/opt/ibm/lsfsuite/lsf/10.1/linux2.6-glibc2.3-x86_64/etc/docker1_monitor.py", line 385, in <module>
    main(sys.argv[1:])
  File "/opt/ibm/lsfsuite/lsf/10.1/linux2.6-glibc2.3-x86_64/etc/docker1_monitor.py", line 378, in main
    if driverMonitor.start_monitor() < 0 :
  File "/opt/ibm/lsfsuite/lsf/10.1/linux2.6-glibc2.3-x86_64/etc/docker1_monitor.py", line 175, in start_monitor
    if self.__collect_rusage() < 0 :
  File "/opt/ibm/lsfsuite/lsf/10.1/linux2.6-glibc2.3-x86_64/etc/docker1_monitor.py", line 225, in __collect_rusage
    self.dbHandler.update_db(resources)
  File "/opt/ibm/lsfsuite/lsf/10.1/linux2.6-glibc2.3-x86_64/etc/docker1_monitor.py", line 131, in update_db
    conn.rollback()
sqlite3.OperationalError: cannot rollback - no transaction is active`

**Comment by huidongchen** [comment]
Re the first issue, it seems something related to your platform. Given this information, i can't say much.

For the second problem, it's indeed a bug. I will fix it in the new version.

**Comment by smk5g5** [comment]
Thanks Huidong,

Another bug I found is that if cell labels have spaces in them e.g. 'CD34+ LMPP' , 'CD34+ Lymphoid UNK', 'CD34+ MDP-1' etc the marker found step throws and error probably because of spaces in cell names. Just wanted to point that out!

**Comment by huidongchen** [comment]
That's good to know. I will look into it as well! Thanks!

**Comment by smk5g5** [comment]
Cool software btw!
