### ISSUE TITLE
no plot output with screen or saved pdf files way

### ISSUE THREAD

**Issue by yiyelinfeng** [pinellolab/STREAM#98]
Hi,

    when I run the example for scRNA-seq: 1.1-STREAM_scRNA-seq (Bifurcation).ipynb. the program is fine, but there is no plot show in the screen or can't save as pdf files with some Futurewarnings.such as:
st.plot_qc(adata,jitter=0.3,log_scale=[0,1,4,5],hist_plot=[0,1,4,5], save_fig=True, fig_name='qc.pdf')
/home/softwares/miniconda3/envs/trajectory/lib/python3.7/site-packages/seaborn/distributions.py:2551: FutureWarning: `distplot` is a deprecated function and will be removed in a future version. Please adapt your code to use either `displot` (a figure-level function with similar flexibility) or `histplot` (an axes-level function for histograms).
  warnings.warn(msg, FutureWarning)
/home/softwares/miniconda3/envs/trajectory/lib/python3.7/site-packages/seaborn/distributions.py:1649: FutureWarning: The `vertical` parameter is deprecated and will be removed in a future version. Assign the data to the `y` variable instead.
  warnings.warn(msg, FutureWarning)
/home/softwares/miniconda3/envs/trajectory/lib/python3.7/site-packages/seaborn/distributions.py:2551: FutureWarning: `distplot` is a deprecated function and will be removed in a future version. Please adapt your code to use either `displot` (a figure-level function with similar flexibility) or `histplot` (an axes-level function for histograms).
  warnings.warn(msg, FutureWarning)
/home/softwares/miniconda3/envs/trajectory/lib/python3.7/site-packages/seaborn/distributions.py:1649: FutureWarning: The `vertical` parameter is deprecated and will be removed in a future version. Assign the data to the `y` variable instead.
  warnings.warn(msg, FutureWarning)
/home/softwares/miniconda3/envs/trajectory/lib/python3.7/site-packages/seaborn/distributions.py:2551: FutureWarning: `distplot` is a deprecated function and will be removed in a future version. Please adapt your code to use either `displot` (a figure-level function with similar flexibility) or `histplot` (an axes-level function for histograms).
  warnings.warn(msg, FutureWarning)
/home/softwares/miniconda3/envs/trajectory/lib/python3.7/site-packages/seaborn/distributions.py:1649: FutureWarning: The `vertical` parameter is deprecated and will be removed in a future version. Assign the data to the `y` variable instead.
  warnings.warn(msg, FutureWarning)
/home/softwares/miniconda3/envs/trajectory/lib/python3.7/site-packages/seaborn/distributions.py:2551: FutureWarning: `distplot` is a deprecated function and will be removed in a future version. Please adapt your code to use either `displot` (a figure-level function with similar flexibility) or `histplot` (an axes-level function for histograms).
  warnings.warn(msg, FutureWarning)
/home/softwares/miniconda3/envs/trajectory/lib/python3.7/site-packages/seaborn/distributions.py:1649: FutureWarning: The `vertical` parameter is deprecated and will be removed in a future version. Assign the data to the `y` variable instead.
  warnings.warn(msg, FutureWarning)

so, how to fix this problem?

**Comment by yiyelinfeng** [comment]
others, there is a error:
st.plot_stream(adata,root='S3',color=['label','Gata1'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/softwares/miniconda3/envs/trajectory/lib/python3.7/site-packages/stream/core.py", line 3151, in plot_stream
    sc_i=sns.scatterplot(x=0,y=1,hue=ann,data=tmp,linewidth=0)
  File "/home/softwares/miniconda3/envs/trajectory/lib/python3.7/site-packages/seaborn/_decorators.py", line 46, in inner_f
    return f(**kwargs)
  File "/home/softwares/miniconda3/envs/trajectory/lib/python3.7/site-packages/seaborn/relational.py", line 798, in scatterplot
    alpha=alpha, x_jitter=x_jitter, y_jitter=y_jitter, legend=legend,
  File "/home/softwares/miniconda3/envs/trajectory/lib/python3.7/site-packages/seaborn/relational.py", line 580, in __init__
    super().__init__(data=data, variables=variables)
  File "/home/softwares/miniconda3/envs/trajectory/lib/python3.7/site-packages/seaborn/_core.py", line 604, in __init__
    self.assign_variables(data, variables)
  File "/home/softwares/miniconda3/envs/trajectory/lib/python3.7/site-packages/seaborn/_core.py", line 668, in assign_variables
    data, **variables,
  File "/home/softwares/miniconda3/envs/trajectory/lib/python3.7/site-packages/seaborn/_core.py", line 895, in _assign_variables_longform
    if val is not None and len(data) != len(val):
TypeError: object of type 'int' has no len()

**Comment by huidongchen** [comment]
It seems something related to the recent update of `seaborn` and `matplotlib`.

can you check their versions and downgrade `seaborn` to `0.10.1` and `matplotlib` to `3.2.2`?

**Comment by yiyelinfeng** [comment]
It works, thanks. but I would like use the python commandline, there is still no plot show on screen.
